#
# makefile
# Parker Piedmont
# CS 240 - Michael Wilder
# 10/18/2019
#

# To build msh, simply run make

all: msh.c
	gcc msh.c -o msh

# Build msh with debugging symbols
all-debug: msh.c
	gcc msh.c -g -o msh

clean:
	rm -f msh